"""Add file fields to Document

Revision ID: 677a87b10c73
Revises: 59b4155ca897
Create Date: 2026-09-07 18:03:52.273198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677a87b10c73'
down_revision: Union[str, Sequence[str], None] = '59b4155ca897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    with op.batch_alter_table('extracted_entities', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('extracted_relationships', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_relationships', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('extracted_entities', schema=None) as batch_op:
        batch_op.alter_column('verification_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
