"""Add case_memberships and case_tasks

Revision ID: 8658cd33f132
Revises: 677a87b10c73
Create Date: 2026-09-09 03:38:57.446948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8658cd33f132'
down_revision: Union[str, Sequence[str], None] = '677a87b10c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_memberships',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('case_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_by', sa.String(length=36), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'user_id', name='uq_case_user_membership')
    )
    with op.batch_alter_table('case_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_case_memberships_case_id', ['case_id'], unique=False)
        batch_op.create_index('ix_case_memberships_status', ['status'], unique=False)
        batch_op.create_index('ix_case_memberships_user_id', ['user_id'], unique=False)
        batch_op.create_index('uq_case_one_active_lead', ['case_id'], unique=True, postgresql_where=sa.text("case_role = 'CASE_LEAD' AND status = 'ACTIVE'"))

    op.create_table('case_tasks',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('completed_by', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('graph_entity_id', sa.String(length=36), nullable=True),
    sa.Column('graph_edge_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_case_tasks_assigned_to', ['assigned_to'], unique=False)
        batch_op.create_index('ix_case_tasks_case_id', ['case_id'], unique=False)
        batch_op.create_index('ix_case_tasks_status', ['status'], unique=False)

    # === Data Migration Step ===
    bind = op.get_bind()
    import uuid
    from datetime import datetime
    
    # 1. Fetch all case_access records
    try:
        access_records = bind.execute(sa.text("SELECT id, user_id, case_id, access_level, assigned_by_user_id, assigned_at, revoked_at, is_active FROM case_access")).fetchall()
        
        # 2. Insert into case_memberships
        for rec in access_records:
            # Map legacy access level
            level = rec.access_level.upper()
            if level in ('MANAGE', 'OWNER', 'LEAD', 'ADMIN'):
                role = 'CASE_LEAD'
            elif level in ('WRITE', 'EDITOR', 'INVESTIGATOR'):
                role = 'INVESTIGATOR'
            elif level in ('REVIEW', 'VERIFIER'):
                role = 'REVIEWER'
            elif level == 'ANALYST':
                role = 'ANALYST'
            else:
                role = 'OBSERVER'
                
            status = 'ACTIVE' if rec.is_active else 'REMOVED'
            
            # Use raw SQL to insert
            bind.execute(
                sa.text('''
                    INSERT INTO case_memberships 
                    (id, case_id, user_id, case_role, status, assigned_by, assigned_at, removed_by, removed_at, created_at, updated_at)
                    VALUES (:id, :case_id, :user_id, :case_role, :status, :assigned_by, :assigned_at, :removed_by, :removed_at, :created_at, :updated_at)
                '''),
                {
                    "id": str(uuid.uuid4()),
                    "case_id": rec.case_id,
                    "user_id": rec.user_id,
                    "case_role": role,
                    "status": status,
                    "assigned_by": rec.assigned_by_user_id,
                    "assigned_at": rec.assigned_at or datetime.utcnow(),
                    "removed_by": None,
                    "removed_at": rec.revoked_at,
                    "created_at": datetime.utcnow(),
                    "updated_at": datetime.utcnow(),
                }
            )
            
    except Exception as e:
        print(f"Skipping case_access data migration due to error or missing table: {e}")
        
    # 3. Ensure each case has a CASE_LEAD
    try:
        cases = bind.execute(sa.text("SELECT id, created_by FROM cases")).fetchall()
        for c in cases:
            lead = bind.execute(sa.text("SELECT id FROM case_memberships WHERE case_id = :case_id AND case_role = 'CASE_LEAD' AND status = 'ACTIVE'"), {"case_id": c.id}).fetchone()
            if not lead:
                if c.created_by:
                    lead_user = c.created_by
                else:
                    # Pick any active member
                    any_member = bind.execute(sa.text("SELECT user_id FROM case_memberships WHERE case_id = :case_id AND status = 'ACTIVE' ORDER BY created_at ASC"), {"case_id": c.id}).fetchone()
                    if any_member:
                        lead_user = any_member.user_id
                    else:
                        # Fallback to a system admin if possible, else skip
                        continue
                        
                bind.execute(
                    sa.text('''
                        INSERT INTO case_memberships 
                        (id, case_id, user_id, case_role, status, assigned_at, created_at, updated_at)
                        VALUES (:id, :case_id, :user_id, 'CASE_LEAD', 'ACTIVE', :now, :now, :now)
                    '''),
                    {
                        "id": str(uuid.uuid4()),
                        "case_id": c.id,
                        "user_id": lead_user,
                        "now": datetime.utcnow()
                    }
                )
    except Exception as e:
        print(f"Skipping CASE_LEAD assignment due to error: {e}")
        
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_case_tasks_status')
        batch_op.drop_index('ix_case_tasks_case_id')
        batch_op.drop_index('ix_case_tasks_assigned_to')

    op.drop_table('case_tasks')
    with op.batch_alter_table('case_memberships', schema=None) as batch_op:
        batch_op.drop_index('uq_case_one_active_lead', postgresql_where=sa.text("case_role = 'CASE_LEAD' AND status = 'ACTIVE'"))
        batch_op.drop_index('ix_case_memberships_user_id')
        batch_op.drop_index('ix_case_memberships_status')
        batch_op.drop_index('ix_case_memberships_case_id')

    op.drop_table('case_memberships')
    # ### end Alembic commands ###
